# Generated by Django 5.2.2 on 2026-07-08 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('email_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='sent', max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('error_message', models.TextField(blank=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_on_comment', models.BooleanField(default=True)),
                ('email_on_like', models.BooleanField(default=True)),
                ('email_on_mention', models.BooleanField(default=True)),
                ('email_on_mentorship', models.BooleanField(default=True)),
                ('email_on_donation', models.BooleanField(default=True)),
                ('email_on_investor_interest', models.BooleanField(default=True)),
                ('email_on_follower_story', models.BooleanField(default=True)),
                ('email_digest', models.BooleanField(default=True)),
                ('email_digest_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('push_on_comment', models.BooleanField(default=True)),
                ('push_on_like', models.BooleanField(default=True)),
                ('push_on_mentorship', models.BooleanField(default=True)),
                ('push_on_donation', models.BooleanField(default=True)),
                ('push_on_investor_interest', models.BooleanField(default=True)),
                ('sms_on_important', models.BooleanField(default=False)),
                ('sms_phone', models.CharField(blank=True, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('story_published', 'Story Published'), ('story_commented', 'Story Commented'), ('story_liked', 'Story Liked'), ('follower_story', 'Follower Posted Story'), ('mentorship_request', 'Mentorship Request'), ('mentorship_accepted', 'Mentorship Accepted'), ('mentorship_rejected', 'Mentorship Rejected'), ('donation_received', 'Donation Received'), ('investor_interested', 'Investor Interested'), ('story_approved', 'Story Approved'), ('story_rejected', 'Story Rejected'), ('comment_reply', 'Comment Reply'), ('achievement_unlocked', 'Achievement Unlocked')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('icon_url', models.URLField(blank=True)),
                ('action_url', models.URLField(blank=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_created', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='stories.story')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'read'], name='notificatio_recipie_6e3964_idx')],
            },
        ),
    ]
